services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./.env
  db:
    image: postgres:16.0
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/


  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - ./.env

  celery:
    build: .

    command: celery -A config worker --loglevel=info

    depends_on:
      - redis
      - db
      - web
    volumes:
      - .:/app
    env_file:
      - .env

  celery-beat:
    build: .

    command: celery -A config beat --loglevel=info

    depends_on:
      - redis
      - db
      - web
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:
