# Generated by Django 4.2 on 2025-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Укажите место, в котором необходимо выполнять привычку",
                max_length=150,
                verbose_name="Место",
            ),
        ),
    ]
